### ISSUE TITLE
K isn't centered (Navbar)

### ISSUE THREAD

**Issue by imaegg11** [imapotatoes11/imapotatoes11.github.io#3]
### The k isn't centered in the navbar... Like it's such an easy fix... It shouldn't be that hard
![image](https://user-images.githubusercontent.com/95944377/230746557-20d378e0-d5e1-4ead-a63b-95890b13005e.png)

**Comment by imapotatoes11** [comment]
### I think I fixed it? does that look centered?
### I commit the change later am working on some major changes atm
###### Yes, I am aware of how small the navbar is
###### No, I have no idea whats causing it (except for centering the navbar I have not touched that part of the code)
![Screenshot 2023-04-08 at 7 25 31 PM](https://user-images.githubusercontent.com/79340132/230746617-e017d61d-a7de-43b1-a7c4-34ac4ab739ea.png)
